apiVersion: v1
kind: Service
metadata:
  name: capstone-project-service
  namespace: capstone-project
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: capstone-project-app
  type: LoadBalancer
