apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-backend-deployment
  namespace: capstone-backend
  labels:
    app: capstone-backend-app
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: capstone-backend-app
  template:
    metadata:
      labels:
        app: capstone-backend-app
    spec:
      containers:
        - name: capstone-backend-service
          image: capstone-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: "2"
              memory: "512Mi"
            requests:
              cpu: "2"
              memory: "512Mi"
          command: [ "python" ]
          args: [ "main.py" ]
          env:
            - name: MONGO_CREDS
              value: '<MONGO_CREDS>'
