apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: capstone-project-ingress
  namespace: capstone-project
  labels:
    app: capstone-project-app
spec:
  ingressClassName: capsone-project-nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: capstone-project-service
                port:
                  number: 5000
status:
  loadBalancer: {}
